# generated by datamodel-codegen:
#   filename:  openapi.json

from __future__ import annotations

from enum import Enum, StrEnum
from typing import Any
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, EmailStr, Field, conint, constr


class Address(BaseModel):
    id: UUID
    label: constr(max_length=50) | None = None
    line1: constr(max_length=200)
    grid_x: conint(ge=-32768, le=32767)
    grid_y: conint(ge=-32768, le=32767)
    notes: constr(max_length=200) | None = None


class BlankEnum(Enum):
    field_ = ''


class Customer(BaseModel):
    id: UUID
    name: constr(max_length=100)
    email: EmailStr
    phone: constr(max_length=30) | None = None
    addresses: list[Address]


class DispatchSnapshot(BaseModel):
    """
    Passthrough — same reasoning as `KitchenSnapshotSerializer`, for
    dispatch's `TripOut`/`CourierOut`.
    """

    trips: Any
    couriers: Any


class KitchenSnapshot(BaseModel):
    """
    Passthrough — kitchen's own `TicketOut`/`OvenOut` (FastAPI/Pydantic)
    are already the wire shape the board wants; gateway doesn't re-model
    them. `None` means kitchen didn't answer (`kitchen_client.get_queue`/
    `get_ovens`'s degrade-not-fail contract), not an empty result.
    """

    queue: Any
    ovens: Any


class MenuAvailability(BaseModel):
    available: bool


class NullEnum(Enum):
    NoneType_None = None


class OrderItem(BaseModel):
    id: UUID
    menu_item: UUID
    qty: conint(ge=0, le=32767)
    unit_price_cents: conint(ge=0, le=2147483647)
    name_snapshot: constr(max_length=100)
    prep_seconds_snapshot: conint(ge=0, le=2147483647)
    bake_seconds_snapshot: conint(ge=0, le=2147483647)


class OrderItemRequest(BaseModel):
    sku: str
    qty: conint(ge=1)


class OrderStatusEnum(StrEnum):
    """
    * `accepted` - accepted
    * `assigned` - assigned
    * `baking` - baking
    * `boxed` - boxed
    * `delivered` - delivered
    * `delivering` - delivering
    * `failed` - failed
    * `picked_up` - picked_up
    * `placed` - placed
    * `prepping` - prepping
    * `queued` - queued
    * `ready` - ready
    * `rejected` - rejected
    """

    accepted = 'accepted'
    assigned = 'assigned'
    baking = 'baking'
    boxed = 'boxed'
    delivered = 'delivered'
    delivering = 'delivering'
    failed = 'failed'
    picked_up = 'picked_up'
    placed = 'placed'
    prepping = 'prepping'
    queued = 'queued'
    ready = 'ready'
    rejected = 'rejected'


class OrderStatusEvent(BaseModel):
    from_status: constr(max_length=20) | None = None
    to_status: constr(max_length=20)
    event: constr(max_length=20)
    occurred_at: AwareDatetime


class OvenStatusStatusEnum(StrEnum):
    """
    * `available` - available
    * `down` - down
    """

    available = 'available'
    down = 'down'


class RejectionReasonEnum(StrEnum):
    """
    * `at_capacity` - at_capacity
    * `item_unavailable` - item_unavailable
    * `outside_range` - outside_range
    """

    at_capacity = 'at_capacity'
    item_unavailable = 'item_unavailable'
    outside_range = 'outside_range'


class ScenarioToggle(BaseModel):
    scenario: str
    active: bool
    overrides: Any
    actions_applied: Any


class ScenariosActive(BaseModel):
    overrides: Any
    scenarios: list[str]


class Speed(BaseModel):
    speed: int


class StationEnum(StrEnum):
    """
    * `prep` - prep
    * `assembly` - assembly
    """

    prep = 'prep'
    assembly = 'assembly'


class TokenRequest(BaseModel):
    """
    Schema-only shape for `POST /auth/token` — either `{email}` (customer)
    or `{username, password}` (staff); `TokenView` validates the real branch
    with `CustomerTokenRequestSerializer`/`StaffTokenRequestSerializer`.
    """

    email: EmailStr | None = None
    username: str | None = None
    password: str | None = None


class TokenResponse(BaseModel):
    access: str
    refresh: str


class MenuItem(BaseModel):
    id: UUID
    sku: constr(max_length=20)
    name: constr(max_length=100)
    description: str | None = None
    base_price_cents: conint(ge=0, le=2147483647)
    prep_seconds: conint(ge=0, le=2147483647)
    bake_seconds: conint(ge=0, le=2147483647)
    oven_slots: conint(ge=-32768, le=32767) | None = None
    station: StationEnum | None = None
    available: bool | None = None
    sort_order: conint(ge=-32768, le=32767) | None = None


class Order(BaseModel):
    id: UUID
    code: constr(max_length=20)
    status: OrderStatusEnum | None = None
    subtotal_cents: conint(ge=0, le=2147483647)
    delivery_fee_cents: conint(ge=0, le=2147483647)
    total_cents: conint(ge=0, le=2147483647)
    placed_at: AwareDatetime
    accepted_at: AwareDatetime | None = None
    promised_at: AwareDatetime | None = None
    ready_at: AwareDatetime | None = None
    delivered_at: AwareDatetime | None = None
    rejection_reason: RejectionReasonEnum | BlankEnum | NullEnum | None = None
    items: list[OrderItem]
    late: bool = Field(
        ...,
        description='Derived, never stored (SPEC.md §2) — now() > promised_at, not terminal.',
    )


class OrderCreateRequest(BaseModel):
    address_id: UUID
    items: list[OrderItemRequest]


class OvenStatus(BaseModel):
    status: OvenStatusStatusEnum


class BoardSnapshot(BaseModel):
    """
    `GET /board/snapshot` (SPEC.md §3.1) — the board's cold-load state.
    """

    orders: list[Order]
    kitchen: KitchenSnapshot
    dispatch: DispatchSnapshot
