# Generated by Django 5.2.16 on 2026-07-27 17:31

import django.db.models.deletion
from django.db import migrations, models

import dinner_rush_core.ids


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=dinner_rush_core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=dinner_rush_core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, default='', max_length=50)),
                ('line1', models.CharField(max_length=200)),
                ('grid_x', models.SmallIntegerField()),
                ('grid_y', models.SmallIntegerField()),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='customers.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
