# Generated by Django 5.2.16 on 2026-07-27 17:31

from django.db import migrations, models

import dinner_rush_core.ids


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.UUIDField(default=dinner_rush_core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('base_price_cents', models.PositiveIntegerField()),
                ('prep_seconds', models.PositiveIntegerField()),
                ('bake_seconds', models.PositiveIntegerField()),
                ('oven_slots', models.SmallIntegerField(default=1)),
                ('station', models.CharField(choices=[('prep', 'prep'), ('assembly', 'assembly')], default='prep', max_length=10)),
                ('available', models.BooleanField(default=True)),
                ('sort_order', models.SmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
