# Generated by Django 5.2.16 on 2026-07-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventTypeCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100, unique=True)),
                ('count', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Outbox',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(unique=True)),
                ('stream', models.CharField(max_length=100)),
                ('envelope', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'outbox',
                'indexes': [models.Index(condition=models.Q(('published_at__isnull', True)), fields=['id'], name='outbox_unpublished')],
            },
        ),
        migrations.CreateModel(
            name='ProcessedEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('consumer_group', models.CharField(max_length=100)),
                ('event_id', models.UUIDField()),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'processed_event',
                'constraints': [models.UniqueConstraint(fields=('consumer_group', 'event_id'), name='processed_event_dedup')],
            },
        ),
    ]
