/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/menu/{sku}/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description `POST /admin/menu/{sku}/availability` — manager only, SPEC.md §3.2. */
        post: operations["v1_admin_menu_availability_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/speed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description `POST /admin/speed` (SPEC.md §3.2) — manager only. */
        post: operations["v1_admin_speed_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description `POST /auth/token` (SPEC.md §3.1).
         *
         *     Staff (kitchen/manager) authenticate with `username`+`password` against
         *     `django.contrib.auth`. Customers authenticate with just their seeded
         *     `email` — there is no signup flow in this phase and the customer table
         *     has no credentials of its own (SPEC.md §1.1); see ADR 0002.
         */
        post: operations["v1_auth_token_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/menu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description `GET /menu` — every item, `available` included so a shortage scenario
         *     can grey items out client-side rather than removing them.
         */
        get: operations["v1_menu_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description `POST /orders` (SPEC.md §3.1). Rejection is a 202, not an error. */
        post: operations["v1_orders_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description `GET /orders/{code}` — customer(own) / manager (SPEC.md §3.1). */
        get: operations["v1_orders_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{code}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description `GET /orders/{code}/timeline` — ordered event history. */
        get: operations["v1_orders_timeline_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Address: {
            /** Format: uuid */
            readonly id: string;
            label?: string;
            line1: string;
            grid_x: number;
            grid_y: number;
            notes?: string;
        };
        /** @enum {unknown} */
        BlankEnum: "";
        Customer: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            /** Format: email */
            email: string;
            phone?: string;
            readonly addresses: components["schemas"]["Address"][];
        };
        MenuAvailability: {
            available: boolean;
        };
        MenuItem: {
            /** Format: uuid */
            readonly id: string;
            sku: string;
            name: string;
            description?: string;
            base_price_cents: number;
            prep_seconds: number;
            bake_seconds: number;
            oven_slots?: number;
            station?: components["schemas"]["StationEnum"];
            available?: boolean;
            sort_order?: number;
        };
        /** @enum {unknown} */
        NullEnum: null;
        Order: {
            /** Format: uuid */
            readonly id: string;
            code: string;
            status?: components["schemas"]["StatusEnum"];
            subtotal_cents: number;
            delivery_fee_cents: number;
            total_cents: number;
            /** Format: date-time */
            readonly placed_at: string;
            /** Format: date-time */
            accepted_at?: string | null;
            /** Format: date-time */
            promised_at?: string | null;
            /** Format: date-time */
            ready_at?: string | null;
            /** Format: date-time */
            delivered_at?: string | null;
            rejection_reason?: (components["schemas"]["RejectionReasonEnum"] | components["schemas"]["BlankEnum"] | components["schemas"]["NullEnum"]) | null;
            readonly items: components["schemas"]["OrderItem"][];
            /** @description Derived, never stored (SPEC.md §2) — now() > promised_at, not terminal. */
            readonly late: boolean;
        };
        OrderCreateRequest: {
            /** Format: uuid */
            address_id: string;
            items: components["schemas"]["OrderItemRequest"][];
        };
        OrderItem: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            menu_item: string;
            qty: number;
            unit_price_cents: number;
            name_snapshot: string;
            prep_seconds_snapshot: number;
            bake_seconds_snapshot: number;
        };
        OrderItemRequest: {
            sku: string;
            qty: number;
        };
        OrderStatusEvent: {
            from_status?: string | null;
            to_status: string;
            event: string;
            /** Format: date-time */
            readonly occurred_at: string;
        };
        /**
         * @description * `at_capacity` - at_capacity
         *     * `item_unavailable` - item_unavailable
         *     * `outside_range` - outside_range
         * @enum {string}
         */
        RejectionReasonEnum: "at_capacity" | "item_unavailable" | "outside_range";
        Speed: {
            speed: number;
        };
        /**
         * @description * `prep` - prep
         *     * `assembly` - assembly
         * @enum {string}
         */
        StationEnum: "prep" | "assembly";
        /**
         * @description * `accepted` - accepted
         *     * `assigned` - assigned
         *     * `baking` - baking
         *     * `boxed` - boxed
         *     * `delivered` - delivered
         *     * `delivering` - delivering
         *     * `failed` - failed
         *     * `picked_up` - picked_up
         *     * `placed` - placed
         *     * `prepping` - prepping
         *     * `queued` - queued
         *     * `ready` - ready
         *     * `rejected` - rejected
         * @enum {string}
         */
        StatusEnum: "accepted" | "assigned" | "baking" | "boxed" | "delivered" | "delivering" | "failed" | "picked_up" | "placed" | "prepping" | "queued" | "ready" | "rejected";
        /**
         * @description Schema-only shape for `POST /auth/token` — either `{email}` (customer)
         *     or `{username, password}` (staff); `TokenView` validates the real branch
         *     with `CustomerTokenRequestSerializer`/`StaffTokenRequestSerializer`.
         */
        TokenRequest: {
            /** Format: email */
            email?: string;
            username?: string;
            password?: string;
        };
        TokenResponse: {
            access: string;
            refresh: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    v1_admin_menu_availability_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sku: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MenuAvailability"];
                "application/x-www-form-urlencoded": components["schemas"]["MenuAvailability"];
                "multipart/form-data": components["schemas"]["MenuAvailability"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MenuItem"];
                };
            };
        };
    };
    v1_admin_speed_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Speed"];
                "application/x-www-form-urlencoded": components["schemas"]["Speed"];
                "multipart/form-data": components["schemas"]["Speed"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Speed"];
                };
            };
        };
    };
    v1_auth_token_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["TokenRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRequest"];
                "multipart/form-data": components["schemas"]["TokenRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
        };
    };
    v1_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"];
                };
            };
        };
    };
    v1_menu_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MenuItem"][];
                };
            };
        };
    };
    v1_orders_create: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderCreateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["OrderCreateRequest"];
                "multipart/form-data": components["schemas"]["OrderCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
        };
    };
    v1_orders_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
        };
    };
    v1_orders_timeline_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderStatusEvent"][];
                };
            };
        };
    };
}
