/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/menu/{sku}/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description `POST /admin/menu/{sku}/availability` — manager only, SPEC.md §3.2. */
        post: operations["v1_admin_menu_availability_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/ovens/{oven_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description `POST /admin/ovens/{id}/status` (SPEC.md §3.2) — manager only. Proxies
         *     to kitchen's write endpoint via a minted service token; the oven-down
         *     chaos button's write path.
         */
        post: operations["v1_admin_ovens_status_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/scenarios/{name}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description `POST /admin/scenarios/{name}/start` (SPEC.md §3.2) — manager only.
         *
         *     Override-driven scenarios (`friday_rush`, `courier_offline`) write their
         *     parameter deltas to Redis with a wall-clock TTL for the simulator to
         *     poll (`GET /scenarios/active`). Action-driven scenarios (`oven_down`,
         *     `ingredient_shortage`) instead execute their `at_seconds: 0` actions
         *     immediately — the revert actions run on `.../stop`. `dispatch_down` has
         *     no `overrides`/`actions` in config at all (it's `manual:`) and is
         *     rejected here on purpose; it stays a `docker compose stop dispatch` demo
         *     step, not a button.
         */
        post: operations["v1_admin_scenarios_start_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/scenarios/{name}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description `POST /admin/scenarios/{name}/stop` (SPEC.md §3.2) — manager only.
         *     Clears any Redis override early and runs the scenario's revert actions
         *     (the `at_seconds > 0` entries) immediately rather than waiting out
         *     `duration_seconds`.
         */
        post: operations["v1_admin_scenarios_stop_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/speed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description `POST /admin/speed` (SPEC.md §3.2) — manager only. */
        post: operations["v1_admin_speed_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description `POST /auth/token` (SPEC.md §3.1).
         *
         *     Staff (kitchen/manager) authenticate with `username`+`password` against
         *     `django.contrib.auth`. Customers authenticate with just their seeded
         *     `email` — there is no signup flow in this phase and the customer table
         *     has no credentials of its own (SPEC.md §1.1); see ADR 0002.
         */
        post: operations["v1_auth_token_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/board/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description `GET /board/snapshot` — kitchen/manager only. Kitchen/dispatch
         *     sections are `None` when that service didn't answer: a degraded panel,
         *     not a failed request — the same "keep gateway working when a peer
         *     isn't" story as order acceptance's capacity-quote fallback, and the
         *     whole point of Streams over pub/sub for Phase 10's recovery demo.
         */
        get: operations["v1_board_snapshot_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["v1_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/menu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description `GET /menu` — every item, `available` included so a shortage scenario
         *     can grey items out client-side rather than removing them.
         */
        get: operations["v1_menu_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description `POST /orders` (SPEC.md §3.1). Rejection is a 202, not an error. */
        post: operations["v1_orders_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description `GET /orders/{code}` — customer(own) / manager (SPEC.md §3.1). */
        get: operations["v1_orders_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{code}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description `GET /orders/{code}/timeline` — ordered event history. */
        get: operations["v1_orders_timeline_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description `GET /scenarios/active` — public, unauthenticated, mirrors
         *     `accounts.views.SpeedView`: the simulator has no service credentials and
         *     no privileged scope (CLAUDE.md §5), so a public poll is the only channel
         *     it has to learn which overrides currently apply.
         */
        get: operations["v1_scenarios_active_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/speed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description `GET /speed` — read-only, unauthenticated.
         *
         *     The no-virtual-clock rule (SPEC.md §5) applies to every client that
         *     schedules a domain-time delay, not just services — the simulator's think
         *     times and dwell times must divide by the live `SPEED` at the point of use
         *     same as everything else, and it has no privileged scope to call the
         *     manager-only `POST /admin/speed` to find out what that value is. The
         *     current speed isn't sensitive, so this is open rather than routed through
         *     a scope that would misrepresent it as one.
         */
        get: operations["v1_speed_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Address: {
            /** Format: uuid */
            readonly id: string;
            label?: string;
            line1: string;
            grid_x: number;
            grid_y: number;
            notes?: string;
        };
        /** @enum {unknown} */
        BlankEnum: "";
        /** @description `GET /board/snapshot` (SPEC.md §3.1) — the board's cold-load state. */
        BoardSnapshot: {
            orders: components["schemas"]["Order"][];
            kitchen: components["schemas"]["KitchenSnapshot"];
            dispatch: components["schemas"]["DispatchSnapshot"];
        };
        Customer: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            /** Format: email */
            email: string;
            phone?: string;
            readonly addresses: components["schemas"]["Address"][];
        };
        /**
         * @description Passthrough — same reasoning as `KitchenSnapshotSerializer`, for
         *     dispatch's `TripOut`/`CourierOut`/`BacklogOut`.
         */
        DispatchSnapshot: {
            trips: unknown;
            couriers: unknown;
            backlog: unknown;
        };
        /**
         * @description Passthrough — kitchen's own `TicketOut`/`OvenOut` (FastAPI/Pydantic)
         *     are already the wire shape the board wants; gateway doesn't re-model
         *     them. `None` means kitchen didn't answer (`kitchen_client.get_queue`/
         *     `get_ovens`'s degrade-not-fail contract), not an empty result.
         */
        KitchenSnapshot: {
            queue: unknown;
            ovens: unknown;
        };
        MenuAvailability: {
            available: boolean;
        };
        MenuItem: {
            /** Format: uuid */
            readonly id: string;
            sku: string;
            name: string;
            description?: string;
            base_price_cents: number;
            prep_seconds: number;
            bake_seconds: number;
            oven_slots?: number;
            station?: components["schemas"]["StationEnum"];
            available?: boolean;
            sort_order?: number;
        };
        /** @enum {unknown} */
        NullEnum: null;
        Order: {
            /** Format: uuid */
            readonly id: string;
            code: string;
            status?: components["schemas"]["OrderStatusEnum"];
            subtotal_cents: number;
            delivery_fee_cents: number;
            total_cents: number;
            /** Format: date-time */
            readonly placed_at: string;
            /** Format: date-time */
            accepted_at?: string | null;
            /** Format: date-time */
            promised_at?: string | null;
            /** Format: date-time */
            ready_at?: string | null;
            /** Format: date-time */
            delivered_at?: string | null;
            rejection_reason?: (components["schemas"]["RejectionReasonEnum"] | components["schemas"]["BlankEnum"] | components["schemas"]["NullEnum"]) | null;
            readonly items: components["schemas"]["OrderItem"][];
            /** @description Derived, never stored (SPEC.md §2) — now() > promised_at, not terminal. */
            readonly late: boolean;
        };
        OrderCreateRequest: {
            /** Format: uuid */
            address_id: string;
            items: components["schemas"]["OrderItemRequest"][];
        };
        OrderItem: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            menu_item: string;
            qty: number;
            unit_price_cents: number;
            name_snapshot: string;
            prep_seconds_snapshot: number;
            bake_seconds_snapshot: number;
        };
        OrderItemRequest: {
            sku: string;
            qty: number;
        };
        /**
         * @description * `accepted` - accepted
         *     * `assigned` - assigned
         *     * `baking` - baking
         *     * `boxed` - boxed
         *     * `delivered` - delivered
         *     * `delivering` - delivering
         *     * `failed` - failed
         *     * `picked_up` - picked_up
         *     * `placed` - placed
         *     * `prepping` - prepping
         *     * `queued` - queued
         *     * `ready` - ready
         *     * `rejected` - rejected
         * @enum {string}
         */
        OrderStatusEnum: "accepted" | "assigned" | "baking" | "boxed" | "delivered" | "delivering" | "failed" | "picked_up" | "placed" | "prepping" | "queued" | "ready" | "rejected";
        OrderStatusEvent: {
            from_status?: string | null;
            to_status: string;
            event: string;
            /** Format: date-time */
            readonly occurred_at: string;
            reason?: (components["schemas"]["RejectionReasonEnum"] | components["schemas"]["BlankEnum"] | components["schemas"]["NullEnum"]) | null;
            queue_depth?: number | null;
        };
        OvenStatus: {
            status: components["schemas"]["OvenStatusStatusEnum"];
        };
        /**
         * @description * `available` - available
         *     * `down` - down
         * @enum {string}
         */
        OvenStatusStatusEnum: "available" | "down";
        /**
         * @description * `at_capacity` - at_capacity
         *     * `item_unavailable` - item_unavailable
         *     * `outside_range` - outside_range
         * @enum {string}
         */
        RejectionReasonEnum: "at_capacity" | "item_unavailable" | "outside_range";
        ScenarioToggle: {
            scenario: string;
            active: boolean;
            overrides: unknown;
            actions_applied: unknown;
        };
        ScenariosActive: {
            overrides: unknown;
            scenarios: string[];
        };
        Speed: {
            speed: number;
        };
        /**
         * @description * `prep` - prep
         *     * `assembly` - assembly
         * @enum {string}
         */
        StationEnum: "prep" | "assembly";
        /**
         * @description Schema-only shape for `POST /auth/token` — either `{email}` (customer)
         *     or `{username, password}` (staff); `TokenView` validates the real branch
         *     with `CustomerTokenRequestSerializer`/`StaffTokenRequestSerializer`.
         */
        TokenRequest: {
            /** Format: email */
            email?: string;
            username?: string;
            password?: string;
        };
        TokenResponse: {
            access: string;
            refresh: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    v1_admin_menu_availability_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sku: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MenuAvailability"];
                "application/x-www-form-urlencoded": components["schemas"]["MenuAvailability"];
                "multipart/form-data": components["schemas"]["MenuAvailability"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MenuItem"];
                };
            };
        };
    };
    v1_admin_ovens_status_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                oven_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OvenStatus"];
                "application/x-www-form-urlencoded": components["schemas"]["OvenStatus"];
                "multipart/form-data": components["schemas"]["OvenStatus"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OvenStatus"];
                };
            };
        };
    };
    v1_admin_scenarios_start_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioToggle"];
                };
            };
        };
    };
    v1_admin_scenarios_stop_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioToggle"];
                };
            };
        };
    };
    v1_admin_speed_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Speed"];
                "application/x-www-form-urlencoded": components["schemas"]["Speed"];
                "multipart/form-data": components["schemas"]["Speed"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Speed"];
                };
            };
        };
    };
    v1_auth_token_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["TokenRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRequest"];
                "multipart/form-data": components["schemas"]["TokenRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
        };
    };
    v1_board_snapshot_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardSnapshot"];
                };
            };
        };
    };
    v1_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"];
                };
            };
        };
    };
    v1_menu_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MenuItem"][];
                };
            };
        };
    };
    v1_orders_create: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderCreateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["OrderCreateRequest"];
                "multipart/form-data": components["schemas"]["OrderCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
        };
    };
    v1_orders_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
        };
    };
    v1_orders_timeline_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderStatusEvent"][];
                };
            };
        };
    };
    v1_scenarios_active_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenariosActive"];
                };
            };
        };
    };
    v1_speed_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Speed"];
                };
            };
        };
    };
}
