# Generated by Django 5.2.16 on 2026-07-27 17:31

import django.db.models.deletion
from django.db import migrations, models

import dinner_rush_core.ids


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCodeSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=dinner_rush_core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('accepted', 'accepted'), ('assigned', 'assigned'), ('baking', 'baking'), ('boxed', 'boxed'), ('delivered', 'delivered'), ('delivering', 'delivering'), ('failed', 'failed'), ('picked_up', 'picked_up'), ('placed', 'placed'), ('prepping', 'prepping'), ('queued', 'queued'), ('ready', 'ready'), ('rejected', 'rejected')], default='placed', max_length=20)),
                ('subtotal_cents', models.PositiveIntegerField()),
                ('delivery_fee_cents', models.PositiveIntegerField()),
                ('total_cents', models.PositiveIntegerField()),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('promised_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, choices=[('at_capacity', 'at_capacity'), ('item_unavailable', 'item_unavailable'), ('outside_range', 'outside_range')], max_length=20, null=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='customers.address')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='customers.customer')),
            ],
            options={
                'ordering': ['-placed_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=dinner_rush_core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('qty', models.PositiveSmallIntegerField()),
                ('unit_price_cents', models.PositiveIntegerField()),
                ('name_snapshot', models.CharField(max_length=100)),
                ('prep_seconds_snapshot', models.PositiveIntegerField()),
                ('bake_seconds_snapshot', models.PositiveIntegerField()),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderStatusEvent',
            fields=[
                ('id', models.UUIDField(default=dinner_rush_core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=20, null=True)),
                ('to_status', models.CharField(max_length=20)),
                ('event', models.CharField(max_length=20)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='orders.order')),
            ],
            options={
                'ordering': ['occurred_at'],
            },
        ),
    ]
