# Generated by Django 5.2.16 on 2026-07-28 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderstatusevent",
            name="queue_depth",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderstatusevent",
            name="reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("at_capacity", "at_capacity"),
                    ("item_unavailable", "item_unavailable"),
                    ("outside_range", "outside_range"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
